export default[
	{key: "address-book-o", name: "地址"},
	{key: "address-book", name: "实心地址"},
	{key: "address-card-o", name: "身份证"},
	{key: "adjust", name: '半日'},
	{key: 'adn', name: '实心A'},
	{key: 'align-center', name: '居中'},
	{key: 'align-justify', name: '居中1'},
	{key: 'align-left', name: '左对齐'},
	{key: 'align-right', name: '右对齐'},
	{key: 'amazon', name: 'a'},
	{key: 'ambulance', name: '救护车'},
	{key: 'american-sign-language-interpreting', name: '2个ok手势'},
	{key: 'anchor', name: '作者'},
	{key: 'android', name: '安卓'},
	{key: 'angellist', name: '剪刀手'},
	{key: 'angle-double-down', name: '向下双箭头'},
	{key: 'angle-double-left', name: '向左双箭头'},
	{key: 'angle-double-right', name: '向右双箭头'},
	{key: 'angle-double-up', name: '向上双箭头'},
	{key: 'angle-down', name: '向下箭头'},
	{key: 'angle-left', name: '向左箭头'},
	{key: 'angle-right', name: '向右箭头'},
	{key: 'angle-up', name: '向上箭头'},
	{key: 'apple', name: '苹果'},
	{key: 'archive', name: '档案文件'},
	{key: 'area-chart', name: '图表'},
	{key: 'arrow-circle-down', name:'向下圆形三角'},
	{key: 'arrow-circle-left'},
	{key: 'arrow-circle-o-down'},
	{key: 'arrow-circle-o-left'},
	{key: 'arrow-circle-o-right'},
	{key: 'arrow-circle-o-up'},
	{key: 'arrow-circle-right'},
	{key: 'arrow-circle-up'},
	{key: 'arrow-down'},
	{key: 'arrow-left'},
	{key: 'arrow-right'},
	{key: 'arrow-up'},
	{key: 'arrows-alt'},
	{key: 'arrows-h'},
	{key: 'arrows-v'},
	{key: 'arrows'},
	{key: 'asl-interpreting'},
	{key: 'assistive-listening-systems'},
	{key: 'asterisk'},
	{key: 'at'},
	{key: 'audio-description'},
	{key: 'automobile'},
	{key: 'backward'},
	{key: 'balance-scale'},
	{key: 'ban'},
	{key: 'bandcamp'},
	{key: 'bank'},
	{key: 'bar-chart-o'},
	{key: 'bar-chart'},
	{key: 'barcode'},
	{key: 'bars'},
	{key: 'bath'},
	{key: 'bathtub'},
	{key: 'battery-0'},
	{key: 'battery-1'},
	{key: 'battery-2'},
	{key: 'battery-3'},
	{key: 'battery-4'},
	{key: 'battery-empty'},
	{key: 'battery-full'},
	{key: 'battery-half'},
	{key: 'battery-quarter'},
	{key: 'battery-three-quarters'},
	{key: 'battery'},
	{key: 'bed'},
	{key: 'beer'},
	{key: 'behance-square'},
	{key: 'behance'},
	{key: 'bell-o'},
	{key: 'bell-slash-o'},
	{key: 'bell'},
	{key: 'bicycle'},
	{key: 'binoculars'},
	{key: 'birthday-cake'},
	{key: 'bitbucket-square'},
	{key: 'bitbucket'},
	{key: 'bitcoin'},
	{key: 'black-tie'},
	{key: 'blind'},
	{key: 'bluetooth-b'},
	{key: 'bluetooth'},
	{key: 'bold'},
	{key: 'bolt'},
	{key: 'bomb'},
	{key: 'book'},
	{key: 'bookmark-o'},
	{key: 'bug'},
	{key: 'building-o'},
	{key: 'building'},
	{key: 'bullhorn'},
	{key: 'bus'},
	{key: 'cab'},
	{key: 'calculator'},
	{key: 'camera'},
	{key: 'car'},
	{key: 'caret-down'},
	{key: 'caret-left'},
	{key: 'caret-right'},
	{key: 'caret-square-o-down'},
	{key: 'caret-square-o-left'},
	{key: 'caret-square-o-right'},
	{key: 'caret-square-o-up'},
	{key: 'caret-up'},
	{key: 'cart-arrow-down'},
	{key: 'cart-plus'},
	{key: 'chain'},
	{key: 'check-circle-o'},
	{key: 'check-circle'},
	{key: 'check-square-o'},
	{key: 'check-square'},
	{key: 'check'},
	{key: 'child'},
	{key: 'chrome'},
	{key: 'clock-o'},
	{key: 'clone'},
	{key: 'close'},
	{key: 'cloud-download'},
	{key: 'viacoin'},
	{key: 'window-close'},
	{key: 'user-o'},
	{key: 'user'},
	{key: 'user-plus'},
	{key: 'user-circle-o'},
	{key: 'user-circle'},
	{key: 'tv'},
	{key: 'twitch'},
	{key: 'upload'},
	{key: 'vcard'},
	{key: 'venus'},
	{key: 'volume-down'},
	{key: 'volume-off'},
	{key: 'volume-up'},
	{key: 'weibo'},
	{key: 'wifi'},
	{key: 'wheelchair'},
	{key: 'tty'},
	{key: 'try'},
	{key: 'truck'},
	{key: 'trophy'},
	{key: 'train'},
	{key: 'toggle-down'},
	{key: 'toggle-up'},
	{key: 'thumb-tack'},
	{key: 'thermometer-0'},
	{key: 'th'},
	{key: 'terminal'},
	{key: 'tag'},
	{key: 'tablet'},
	{key: 'table'},
	{key: 'support'},
	{key: 'sun-o'},
	{key: 'sticky-note'},
	{key: 'steam'},
	{key: 'spinner'},
	{key: 'sort'},
	{key: 'shower'},
	{key: 'ship'},
	{key: 'share'},
	{key: 'share-alt'},
	{key: 'rss'},
	{key: 'reply'},
	{key: 'repeat'},
	{key: 'reorder'},
	{key: 'refresh'},
	{key: 'remove'},
	{key: 'registered'},
	{key: 'print'},
	{key: 'plug'},
	{key: 'play'},
	{key: 'play-circle'},
	{key: 'play-circle-o'},
	{key: 'plane'},
	{key: 'pause'},
	{key: 'paste'},
	{key: 'neuter'},
	{key: 'modx'},
	{key: 'mars'},
	{key: 'medkit'},
	{key: 'map'},
	{key: 'male'},
	{key: 'lock'},
	{key: 'list'},
	{key: 'leaf'},
	{key: 'level-down'},
	{key: 'level-up'},
	{key: 'life-ring'},
	{key: 'link'},
	{key: 'jpy'},
	{key: 'heart'},
	{key: 'paw'}
]