//简体中文
export default {
    name: 'zh-cn',
    //权限编码
    power: {
        add: '添加',
        look: '查看',
        modify: '修改',
        edit: '编辑',
        remove: '删除',
        search: '搜索',
        reset: '重置',
        allRemove: '批量删除',
        import: '导入',
        export: '导出',
        bing: '绑定',
        menuPower: '菜单权限',
        sendAdd: '发送追加',
        sendEdit: '发送修改',
        sendDelAll: '发送删除所有',
        sendUpdate: '发送更新',
        sendDown: '下发',
        upload: '上传',
        send: '发送'
    },
    //页面操作
    action: {
        all: '全部',
        operation: '操作',
        confirm: '确定',
        cancel: '取消',
        save: '保存',
        back: '返回',
        allChoose: '全选',
        reset: '重置',
        other: '其他',
        confirmIsRemove: '您是否要进行删除操作!',
        cancelRemove: '取消删除',
        removeSuccess: '删除成功!',
        removeFail: '删除失败',
        addSuccess: '添加成功!',
        addFail: '添加失败!',
        modifySuccess: '修改成功',
        modifyFail: '修改失败',
        updateSuccess: '更新成功',
        updateError: '更新失败',
        exit: '您的登录已超时,请重新登录!',
        unexit: '未登录',
        noPromise: '暂无权限',
        actionError: '操作失败',
        addOverlay: '请在地图在添加围栏',
        actionSuccess: '操作成功',
        tip: '提示',
        orderSuccess: '指令成功下发',
        noticeSuccess: '报警确认成功',
        noticeFail: '报警确认失败',
        sendDown: '下发'
    },
    //文本控件类提示
    placeholder: {
        inputValue: '请输入内容',
        selectValue: '请选择',
        selectDate: '选择日期',
        roleCopy: '角色权限复制'
    },
    //公用模块语言包
    common: {
        //公司
        enterprise: {
            affiliated: "所属公司",
            enterpriseName: "公司名称"
        },
        //车辆
        vehicle: {
            plateCode: '车牌号'
        },
        //报警相关
        alarm: {
            later: '稍后提示',
            closed: '秒后自动关闭',
            alarmWacth: '报警记录',
            alarmTypeName: '报警类型',
            time: '报警时间',
            messageText: '报警内容',
            serious: '紧急报警',
            intermediate: '中级报警',
            ordinary: '一般报警'
        },
        //指令状态及类型相关
        order: {
            'orderWacth': '指令追踪',
            text: '文本',
            video: '视频',
            off_oli: '断油',
            off_power: '断电',
            lock_car: '锁车',
            photo: '拍照',
            type: '指令类型',
            sendDate: '下发时间',
            orderContent: '状态',
            status: {
                0: "初始",
                1: "成功",
                2: "设备不在线",
                3: "失败",
                4: "等待回应超时",
                5: "等待回应中",
                6: "作废",
                7: "指令已下达，正在等待响应"

            },
            orderType: {
                WCF0x8600: "设置圆形区域",
                WCF0x8604: "设置多边形区域",
                WCF0x8602: "设置矩形区域",
                WCF0x8606: "设置路线",
                WCF0x8601: "删除区域",
                WCF0x8801: "拍照命令",
                WCF0x8300: "文本下发命令",
                WCF0x8804: "录音命令",
                WCF0x8201: "点名指令/位置信息查询",
                WCF0x8400: "电话回拨菜单",
                WCF0x8104: "查询终端参数",
                WCF0x8103: "设置终端参数",
                WCF0x8001: '报警确认',
                WCF0x86FF: '设置渣土区域',
                WCF0x8F800x19: '车辆扩展控制',
                WCF0x8400: '电话回拨',
                WCF0x8203: '单条报警确认',
                WCF0x87000x0808: '采集指定的行驶速度记录',
                WCF0x87000x0809: '采集指定的位置信息记录',
                WCF0x87000x0816: '采集指定的事故疑点记录',
                WCF0x87000x0817: '采集指定的超时驾驶记录',
                WCF0x87000x0818: '采集指定的驾驶人身份记录',
                WCF0x87000x0819: '采集指定的外部供电记录',
                WCF0x87000x0820: '采集指定的参数修改记录',
                WCF0x87000x0821: '采集指定的速度状态日志',
                WCF20030x87000x0102: '采集记录仪的实时时钟',
                WCF20030x87000x0101: '采集当前驾驶人',
                WCF0x87000x0000: '采集记录仪执行标准版本',
                WCF0x87000x0001: '采集当前驾驶人信息',
                WCF0x87000x0002: '采集记录仪实时时间',
                WCF0x87000x0003: '采集累计行驶里程',
                WCF0x87000x0004: '采集记录仪脉冲系数',
                WCF0x87000x0005: '采集车辆信息',
                WCF0x87000x0006: '采集记录仪状态信号配置信息',
                WCF0x87000x0007: '采集记录仪唯一性编号',
                WCF0x8803: '多媒体上传',
                WCF0x880101: '录像命令',
                WCF0x8201: '位置信息查询',
                WCF0x8202: '临时位置跟踪控制',
                WCF0x8401: '设置电话本',
                WCF0x8301: '事件设置',
                WCF0x8302: '提问下发',
                WCF0x8900: '数据透传下发',
                WCF0x8805: '单条存储多媒体数据检索上传命令',
                WCF0x8303: '信息点播菜单设置',
                WCF0x8302: "提问下发",
                WCF0x87000x82:"车辆设置信息",
                WCF0x87000x830:'设置记录仪初次安装日期',
                WCF0x87000x84:'设置状态量配置信息',
                WCF0x87000x831:'设置记录仪时间',
                WCF0x87000xC3:'设置记录仪脉冲系数',
                WCF0x87000xC4:'设置初始里程',
                WCF0x8500:'车辆控制',
                WCF0x8802:'多媒体检索',
                WCF0x8803:'多媒体上传',
                WCF0x8107:'查询终端属性',
                WCF0x8702:'上报驾驶员身份信息请求',
                WCF0x81051:'无线升级',
                WCF0x8108:'北斗下发终端升级包',
                WCF0x81052:'控制终端连接指定服务',
                WCF0x81053:'终端关机',
                WCF0x81054:'终端复位',
                WCF0x81055:'终端恢复出厂设置',
                WCF0x81056:'关闭数据通信',
                WCF0x81057:'关闭所有无线通信',
            }
        },
        //围栏
        fence: {
            //围栏类型
            circle: '圆形',
            rectangle: '矩形',
            polygon: '多边形',
            line: '线路',
            //围栏区域属性
            1: '根据时间',
            2: '限速',
            4: '进区域报警给驾驶员',
            8: '进区域报警给平台',
            16: '出区域报警给驾驶员',
            32: '出区域报警给平台',
            256: '禁止开门(默认允许)',
            512: '装货区域',
            1024: '禁区',
            2048: '倾倒区域',
            16384: '进区域关闭通信模块(默认开启)',
            32768: '进区域不采集GNSS详细定位数据(默认采集)',
        },
        fenceZt: {
            256: '重车限速',
            512: '开盖限速',
            1024: '重车开盖限速',
            2048: '限举',
            4096: '重车限举'
        },
        sex: {
            0: '女',
            1: '男',
        },
        userType: {
            1: '个人用户',
            2: '普通用户',
            3: '运维用户',
            4: '默认公司管理员',
            5: '超级管理员',
        },
        roleType: {
            0: '超级管理员',
            1: '公司默认角色',
            2: '运维角色',
            3: '普通角色',
        },
    },
    //后端错误编码包
    error: {
        207: '频繁操作',
        208: '暂无数据',
        2081: '用户不存在',
        2082: '角色不存在',
        303: '登录失败',
        3031: '帐号或者密码不存在',
        3032: '帐号禁止登录',
        3033: '密码错误',
        3034: '短信验证码错误',
        400: '请求参数出错',
        401: '没有登录',
        402: '重新登录',
        403: '没有权限',
        4031: '公司下有车队不能删除',
        4032: '车队下有车不能删除',
        4035: '设备厂商已绑定',
        4036:'设备已注册',
        404: '请求地址错误',
        408: '请求超时',
        409: '发生冲突',
        410: '已被删除',
        423: '已被锁定',
        4230: '车辆和设备未绑定',
        4231: '车辆已与设备绑定',
        4000: '不能重复',
        4001: '公司名字重复',
        4002: '同节点车队名字重复',
        4003: '用户名字重复',
        4006: '角色名称重复',
        4007: '操作编码重复',
        4008: '菜单名称重复',
        4009: '设备能力项名称重复',
        4010: '设备通讯项名称重复',
        4011: '设备手机号重复',
        4012: '相同制造上编号的终端编号不能重复',
        4013: '车辆车牌号不能重复',
        4014: '设备厂商名称不能重复',
        4015: '终端型号或制造商编号重复',
        4016: '手机号不能重复',
        4017: '驾驶证号不能重复',
        4018: '设备通讯项版本不能重复',
        4037: '该公司下有子公司不能删除',
        40018: '司机已经绑定车辆，禁止修改公司',
        40019: '司机已经绑定车辆，禁止删除',
        2082: '用户角色不存在',
        500: '服务器出错',
        5100: '添加失败',
        5200: '删除失败 ',
        5201: '删除菜单失败',
        5202: '删除操作失败',
        5203: '删除角色失败',
        5204: '删除用户失败',
        5300: '修改失败',
        5301: '修改菜单失败',
        5302: '修改用户失败',
        5001: '用户注册失败',
        5002: '新增角色失败',
        5003: '新增菜单失败',
        600: '参数不能为空',
        6001: '模块不能为空',
        7000: '围栏ID不存在',
        7001: '添加围栏与车辆绑定失败',
        7002: '当前围栏不能删除',
        7003: '围栏删除失败',
        7004: '车辆不在线',
        7005: '更新围栏失败',
        40010: '手机号不能为空',
        40011: '所属公司不能为空',
        40012: '驾驶证号不能为空',
        9001: '请选择所属角色或用户权限',
        4231: '车辆和设备已绑定',
        40017: '当前角色已经绑定用户,禁止删除',
        7007: '围栏名称不能重复',
        7009: '当前车辆不能下发此围栏',
        7010: '设备未绑定协议',
        7011: '没有选择车辆',
        7015:'暂无车辆限制操作权限',
        7101: '指令下发失败',
        7102: '指令下发JSON转换错误',
        7103: '指令下发设备没有SIM卡号',
        7105:'指令协议版本不匹配',
        104: '指令下发没有选择行',
        7106: '请正确输入车牌号码',
        7107: '记录ID值已存在,保存失败',
        7108: 'ID数值不能大于SMALLINT的取值范围(-327678,32767),此处只允许正整数',
        7109:'选择车辆与媒体ID不匹配',
        7110:'已被使用不可删除',
        8008:'车辆注销失败',
        7112:'设备注销',
        7113:'设备注销失败',
        7104:'未选择信息',
        7114:'账号已存在',
        10001:'改服务已绑定不能操作',
        7118:'角色权限不能为空',
        7120:'ID不可修改，已被外键使用',
        7111:'车辆在线不可注销',
        7116:'车辆未绑定围栏',
        8009:'导入文件内容错误',
        20005:'上传异常',
        20003:'上传文件为空',
        20004:'连接ftp失败'
    },
    //路由语言包
    routerName: {
        home: '首页',
        multiCar: '多车监控',
        fenceManage: '围栏管理',
        fenceSend: '围栏下发',
        alarmSearch: '报警统计',
        multimediaManage: '多媒体管理',
        terminalParamSet: '终端参数设置',
    },
    //视频操作返回的代码
    videoErrorCode: {
        0: '成功',
        1: '录像状态为开始状态',
        2: '录像状态为结束状态',
        2000: '服务器连接掉线',
        2001: '未知错误',
        2002: '参数错误',
        2003: '返回参数错误',
        2004: '未初始化',
        2005: '命令错误',
        2006: '新连接错误',
        2007: '发送错误',
        2008: '内存不足',
        2009: '资源错误',
        2010: '文件不存在',
        2011: '超过可访问数',
        2012: '创建网络套接字出错',
        2013: '套接字出错',
        2014: '连接出错',
        2015: '绑定出错',
        2016: '监听出错',
        2017: '发送出错',
        2018: '接收出错',
        2019: '超时',
        2020: '超出通道限制',
        2021: '设备忙',
        2022: '擦除出错',
        2023: '校验出错',
        2024: '系统资源冲突',
        2025: '系统忙',
        2026: '用户名冲突',
        2027: '超过连接限度',
        2028: '数据类型错误',
        2029: '用户不存在',
        2030: '密码错误',
        2030: '密码错误',
        2031: 'MAC地址错误',
        2032: '重复登录',
        2033: '未登录',
        2034: '超出最大回放数',
        2035: '系统在升级',
        2036: '下载失败',
        2037: '文件打开失败',
        2038: '用户已停止',
        2039: '串口重复打开',
        2040: '获取本地MAC地址失败',
        2041: '校验失败',
        2042: '接受失败',
        2043: '发送升级文件失败',
        3000: '视频窗口未连接',
        3001: '视频窗口未开始录像',
        3002: '窗口音频未打开',
        3003: '设备不在线',
        3004: '已连接语音对讲',
        3005: '设备未选择',
        3006: '设备录像文件正在搜索',
        3007: '没有搜索到录像文件',
        3008: '下载录像文件名错误',
        3009: '下载录像路径错误',
        3010: '下载录像错误',
        3011: '远程升级文件路径为空',
        3012: '远程升级文件打开失败',
        3013: '远程升级文件长度为 0',
        3014: '视频窗口已连接',
        3015: '透明串口未打开',
        3016: '文件转换源文件打开错误',
        3017: '文件转换目标文件打开错误',
        3018: '文件转换文件读错误',
        3018: '文件转换文件写错误',
        
    },
    //过滤语言包
    filter: {
        notEmpty: '内容不能为空!',
        register: '注册',
        online: '在线',
        offline: '离线',
        unknown: '未知',
        all: "全部",
        onStatus: '使用',
        noStatus: '停用',
        noregister: '未注册',
        noempty: '内容不能为空',
        Length: '长度在 {{:min}} 到 {{:max}} 个字符',
        type1: '只能为中文',
        type2: '只能为数字',
        type3: '只能为字母',
        type4: '只能为中文、字母、数字、_',
        type5: '只能为中文、字母',
        type6: '不符合规则',
        type7: '只能为大写字母，数字',
        type8: '首位必须为字母且长度不少于8位',
        type9: '只能为数字、字母',
        type10: '请输入正确的手机号码',
        type11: '输入真实有效的身份证号',
        type12: "只能为中文、字母、数字",
        type13: "IP格式不正确",
        type14: "只能为数字且首位不能为0",
        type15: "请输入1~65535的端口号",
        colorBlue: '蓝色',
        colorYellow: '黄色',
        colorBlack: '黑色',
        colorWhite: '白色',
        colorGreen: '绿色',
        color: '其他',
        FixedLength: "长度只能为{{:len}}位",
        LeastLength: "长度至少17位",
        characters: '只能是5个字符以内的中文',
        picture: "图像",
        music: "音频",
        video: "视频",
        jpg: "JPEG",
        tif: "TIF",
        mp3: "MP3",
        wav: "WAV",
        wmv: "WMV",
        incident0: "平台下发指令",
        incident1: "定时动作",
        incident2: "抢劫报警触发",
        incident3: "碰撞侧翻报警触发"
    },
    //elementUI语言包
    el: {
        colorpicker: {
            confirm: '确定',
            clear: '清空'
        },
        datepicker: {
            now: '此刻',
            today: '今天',
            cancel: '取消',
            clear: '清空',
            confirm: '确定',
            selectDate: '选择日期',
            selectTime: '选择时间',
            selectDateTime: '选择日期时间',
            startDate: '开始日期',
            startTime: '开始时间',
            endDate: '结束日期',
            endTime: '结束时间',
            year: '年',
            month1: '1 月',
            month2: '2 月',
            month3: '3 月',
            month4: '4 月',
            month5: '5 月',
            month6: '6 月',
            month7: '7 月',
            month8: '8 月',
            month9: '9 月',
            month10: '10 月',
            month11: '11 月',
            month12: '12 月',
            // week: '周次',
            weeks: {
                sun: '日',
                mon: '一',
                tue: '二',
                wed: '三',
                thu: '四',
                fri: '五',
                sat: '六'
            },
            months: {
                jan: '一月',
                feb: '二月',
                mar: '三月',
                apr: '四月',
                may: '五月',
                jun: '六月',
                jul: '七月',
                aug: '八月',
                sep: '九月',
                oct: '十月',
                nov: '十一月',
                dec: '十二月'
            }
        },
        select: {
            loading: '加载中',
            noMatch: '无匹配数据',
            noData: '无数据',
            placeholder: '请选择'
        },
        cascader: {
            noMatch: '无匹配数据',
            loading: '加载中',
            placeholder: '请选择'
        },
        pagination: {
            goto: '前往',
            pagesize: '条/页',
            total: '共 {total} 条',
            pageClassifier: '页'
        },
        messagebox: {
            title: '提示',
            confirm: '确定',
            cancel: '取消',
            error: '输入的数据不合法!'
        },
        upload: {
            delete: '删除',
            preview: '查看图片',
            continue: '继续上传'
        },
        table: {
            emptyText: '暂无数据',
            confirmFilter: '筛选',
            resetFilter: '重置',
            clearFilter: '全部',
            sumText: '合计'
        },
        tree: {
            emptyText: '暂无数据'
        },
        transfer: {
            noMatch: '无匹配数据',
            noData: '无数据',
            titles: ['列表 1', '列表 2'],
            filterPlaceholder: '请输入搜索内容',
            noCheckedFormat: '共 {total} 项',
            hasCheckedFormat: '已选 {checked}/{total} 项'
        }
    },
    //全局字典类型语言包
    typeFac: {},
    //业务功能模块语言包
    companyManage: {
        num: '序号',
        menuName: '菜单名称',
        menuUrl: '菜单路径',
        menuIcon: '菜单图标',
        ph: '输入关键字进行过滤',
        ph1: '请输入内容',
        baseInfo: '基础信息',
        ename: '公司名称',
        gmaccount: '管理员帐号',
        ecode: '公司编号',
        eshortName: '公司简称',
        orgCode: '组织机构代码',
        fid: '法人身份证号',
        fname: '法人姓名',
        efox: '公司传真',
        ephone: '公司电话',
        email: '公司邮编',
        eaddress: '公司地址',
        emenu: '公司菜单',
        eManage: '公司管理',
        addC: '添加公司',
        tip: '不能修改本级公司',
        editC: '修改公司',
        tip1: '请选择公司',
        tip2: '此操作将永久删除, 是否继续?',
        tip3: '提示',
        cf: '确定',
        cc: '取消',
        n: '名称',
        icon: '图标',
        fk: '内容不能为空',
        length: '长度在 2 到 15 个字符',
        parentCompany: '上级公司',
        menuManage: '菜单管理',
        tipType1: "不符合规则",
        addMenu: '添加菜单',
        addMenuGroup: '添加菜单分组',
        editMenu: '修改菜单',
        addMenuM: "添加菜单(支持多选)",
        tip4: '该组有分组存在不允许再添加下级菜单',
        operationSuccess: '操作成功',
        tip5: '未添加菜单，无法新建公司',
        ecarType: '公司运营车辆类型',
        mapType: '地图类型',
        sameName: '公司名称已存在',
        sameRoleName: '管理员账号已存在'
    },
    superiorP:{
        agreement: '协议名称',
        MonitorServer: '主链路IP',
        PortMonitorMain: '主链路端口',
        USERID: '用户id',
        PASSWORD: '密码',
        MSG_GNSSCENTERID: '唯一接入码',
        Brightness: '亮度',
        Chromaticity: '色度',
        Contrast: '对比度',
        Quality: '图片质量',
        Saturation: '饱和度',
        IA1: '加密参数IA1',
        KeepMainSec: '主链路保持间隔',
        IC1: '加密参数IC1',
        M1: '加密参数M1',
        MonitorIP: '从链路IP',
        MonitorPort: '从链路端口',
        BackMonitorServer: '连接从链路IP',
        platform: '平台名称',
        bind809:'809服务绑定',
        isAutoLink:'是否自动连接',
        isAutoLinkR:'是否自动重连'
    },
    UserManage: {
        remark: '备注',
        createTime: '创建时间',
        account: '用户帐号',
        username: '用户姓名',
        roleNames: '所属角色',
        accountType: '用户类型',
        operation: '操作',
        selectCompany: '请先选择所属公司',
        basicInformation: '基本信息',
        wellmadestarm: '所属公司',
        accountNumber: '账号',
        role: '所属角色',
        name: '姓名',
        userType: '用户类型',
        userDescribe: '用户描述',
        gender: '性别',
        dateOfBirth: '出生日期',
        postalcode: '邮政编码',
        telephone: '固定电话',
        identityCard: '身份证',
        fax: '传真',
        mailbox: '邮箱',
        mobilePhone: '手机',
        address: '地址',
        usePermission: '用户权限',
        carsPermission: '车组权限',
        actionSuccess: '操作成功',
        actionError: '操作失败',
        cancelRemove: '已取消删除',
        vehicleLimit: '用户车辆限制权限'
    },
    role: {
        company: '公司名称',
        roleName: '角色名称',
        remark: '角色描述',
        createTime: '创建时间',
        operation: '操作',
        changeCompany: '请选择所属公司',
        actionSuccess: '操作成功',
        actionError: '操作失败',
        cancelRemove: '已取消删除',
        modifyRole: '修改角色',
        type1: '正在拼命加载中',
        message: '基础信息',
        roleType: '角色类型',
        roleRemark: '角色描述',
        roleCheckedUser: '授权用户',
        noCheckedUser: '未授权用户',
        yCheckedUser: '已授权用户',
        xiang: '项',
        rolePermission: '角色权限',
    },
    dm: {
        company: '所属公司',
        status: '注册状态',
        terminalType: '终端型号',
        terminalTel: '终端SIM卡号',
        bindingCar: '绑定车辆',
        operation: '操作'
    },
    vt: {
        vehicleType: '车辆类型',
        limitPeople: '载客限员',
        weight: '自重',
        motorBrand: '发动机品牌',
        vehicleBrand: '车辆品牌',
        carFactory: '车厂名称',
        company: '公司名称',
        brand: '品牌名称',
        remark: '备注信息',
        company1: '公司名称:',
        brand1: '品牌名称:',
        carFactory1: '车厂名称:',
        vehicleType1: '车辆类型:',
        weight1: '自重:',
        limitPeople1: '载客限员:',
        oilType1: '燃油类型:',
        electric1: '电压:',
        motorNum1: '发动机号:',
        motorBrand1: '发动机品牌:',
        motorStandard1: '发动机标准转速:',
        motorType1: '发动机型号:',
        tyre1: '轮胎半径:',
        speed1: '后桥转比:',
        getTer: '添加设备',
        drive: '添加司机',
        isPlateCode: '车牌号已存在',
        carType1: '集装箱车',
        carType2: '大件运输车',
        carType3: '保温冷藏车',
        carType4: '商品车运输专用车辆',
        carType5: '罐车',
        carType6: '牵引车',
        carType7: '挂车',
        carType8: '平板车',
        carType9: '危险品运输车',
        carType10: '农用车',
        carType11: '轮式拖拉机',
        carType12: '手扶拖拉机',
        carType13: '履带拖拉机',
        carType14: '特种拖拉机',
        carType15: '大型客车',
        carType16: '中型客车',
        carType17: '小型客车',
        carType18: '轿车',
        carType19: '大型卧铺客车',
        carType20: '中型卧铺客车',
        carType21: '大型普通货车',
        carType22: '中型普通货车',
        carType23: '小型普通货车',
        carType24: '环卫车',
        carType25: '渣土车'

    },
    mM: {
        import: '导入',
        export: '导出',
        Menumanagement: '菜单管理',
        Menudescription: '菜单描述',
        Menufunction: '菜单功能',
        icon: '图标',
        Accessaddress: '访问地址',
        Menusorting: '菜单排序',
        Menuname: '菜单名称',
        Essentialinformation: '基本信息',
        Menueditor: '菜单编辑',
        pleaseenter: '请输入内容',
        addressUrl: '路径',
        menuType: '类型',
        menuMessage: '管理',
        menuMotinon: '监控',
        tipDriveEncode: '请输入正确的驾驶证编号',
        customer: '客户端'

    },
    cM: {
        administratorAccount: '管理员账号',
        Companynumber: '公司编号',
        Organizationcode: '组织机构代码',
        identificationNumber: '法人身份证号',
        Companyaddress: '公司地址',
        CompanyFax: '公司传真',
        Companycode: '公司邮编',
        identificationName: '法人姓名',
        Provinceproper: '所属省市区',
        CompanyTel: '公司电话',
        CompanyMenu: '公司菜单管理',
        menuName: '菜单名称',
        Menuplatform: '菜单所属平台'
    },
    carFactory: {
        carname: '车厂名称',
        carname1: '车厂名称:',
        createTime: '创建时间',
        createTime1: '创建时间:'
    },
    brand: {
        brandName: '品牌名称',
        carname: '车厂名称',
        remark: '备注信息'
    },
    dM: {
        name: '姓名',
        driveName: '司机姓名',
        sex: '性别',
        tel: '电话',
        driveCode: '驾驶证号',
        startmode: '启动状态',
        rolePermission: '用户权限',
        message: '基础信息',
        carPermission: '车组权限',
        code: '账户',
        telPhone: '手机号',
        man: '男',
        woman: '女',
        shortName: '别名',
        remark: '备注',
        email: '邮箱',
        protocol: '协议号'
    },
    pM: {
        permissionName: '权限名称',
        permissionCode: '权限编码',
        addDate: '添加日期',
        addPerson: '添加人员'
    },
    cE: {
        carNumber: '车牌号码',
        carColor: '车牌颜色',
        carCode: '设备编码',
        endPhone: '终端SIM卡号',
        regStatus: '注册状态',
        useStatus: '使用状态',
        onlineStatus: '在线状态',
        bindGroup: '绑定车组',
        carNumbers: '车牌号码(颜色)',
        ownCar: '所属车组',
        choesCar: '选中车组',
        upStatusSus: '启用成功',
        upStatusErr: '启用失败',
        upUserSus: '停用成功',
        upUserErr: '停用失败',
        unbindSus: '解绑成功',
        unbindErr: '解绑失败',
        changEqSus: '更换设备成功',
        changEqErr: '更换设备失败',
        bindEq: "绑定设备",
        unbindEq: "解绑设备",
        changEq: "更换设备",
        useCar: '启用车辆',
        disCar: '停用车辆',
        selectEqu: "请选择设备！"
    },
    cL: {
        vechicleCar: '车辆识别代码/车架号',
        carNumber: '车牌号',
        carColor: '车牌颜色',
        subGroup: '所属分组',
        carType: '车辆类型',
        nextCode: '内部编码',
        carBrand: '车辆品牌',
        carModel: '车辆型号',
        factName: '厂家名称',
        equipment: '设备',
        drive: '司机',
        driveName: '车主姓名',
        drivePhone: '车主手机号',
        vehicLisence: '车辆行车证',
        carPhone: '车身照片',
        equipmentType: '视频设备类型:',
        accessID: '视频设备访问ID:',
        userChannels: '用户通道数:',
        serverPort: '服务器端口:',
        ipAddress: '服务器IP地址:',
        username: '登陆用户名称:',
        loginPassword: '登陆用户名密码:'

    },
    dD: {
        xuNumber: '序号',
        texttype: '字典类型',
        typeName: '类型名称',
        choess: '对应值',
        drivert: '说明',
        bei: '备注'
    },
    vgEscrow: {
        company: '所属公司',
        plateCode: '车牌号',
        terminalCode: '终端SIM卡号',
        mobile: '手机号',
        useStatus: '使用状态',
        onlineStatus: '在线状态',
        isLogOut: '注册状态',
        operation: '操作',
        chooseCar: '选择代管车辆',
        use: '使用',
        stop: '停用',
        isLog: '已注册',
        isOut: '未注册',
        all: '全部',
        online: '在线',
        offline: '离线'
    },
    vgPower: {
        vehicleList: '车辆列表',
        typePlateCode: '请输入车牌号码',
        plateCode: '车牌号码',
        plateColor: '车牌颜色',
        vehicleUseStatus: '车辆使用状态',
        terminalCode: '设备编码',
        empowerList: '授权列表',
        typeAccount: '请输入用户账号',
        account: '账号',
        userName: '姓名',
        sexy: '性别',
        mobilePhone: '手机号码',
        bindingVehicle: '绑定车辆',
        userList: '用户列表',
        vg: '车组',
        bindSuccess: '绑定成功',
        bindError: '绑定失败',
        choseVehicle: '请选择车辆',
        choseAccount: '请选择用户',
        add: '添加 >',
        v: '车辆',
        vall: '所有车辆',
        u: '用户',
        uall: '所有用户',
        male: '男',
        female: '女'
    },
    terminal: {
        company: '所属公司',
        company1: '所属公司:',
        isLogOut: '注册状态',
        terminalType: '终端型号',
        terminalType2: '终端型号:',
        terminalType1: '制造商编号&型号:',
        terminalTel: '终端SIM卡号',
        terminalTel1: '终端SIM卡号:',
        bindingCar: '绑定车辆',
        manufacturer: '制造商名称:',
        code: '终端编号:',
        code1: '终端编号',
        Can: 'Can版本协议:',
        versionProtocol: '终端版本协议:',
        plateCode: '车牌号码:',
        isLog: '已注册',
        isOut: '未注册',
        incorrect: "格式不正确",
        uppercase: "必须为大写字母或数字",
        length7: "长度必须为7位",
        phone: "终端SIM卡号已存在",
        codeNum: "终端编号已存在",
        placeholder: '请选择',
        length11: "长度必须为11位",
        teminTypes: "制造商编号&型号不能为空"
    },
    terminalProM: {
        terminalCode: '制造商编号',
        terminalCode1: '制造商编号:',
        name: '名称',
        contactsPerson: '联系人',
        phoneNumber: '手机号码',
        remark: '备注',
        typeCorrectNum: '请输入正确的手机号',
        sameName: '制造商名称重复'
    },
    deviceManage: {
        manufacturerName: '制造商',
        deviceType: '终端型号',
        makerNum: '制造商编号',
        selectMaker: '制造商选择',
        rule1: '字母或数字',
        rule2: '不能超过15位',
        rule3: '编号只能为数字,且第一位不能为0',
        rule4: '编号长度为5位',
        ph: '请选择'
    },
    fenceManage: {
        ruleName: '围栏名称',
        ruleType: '围栏类型',
        areaType: '围栏属性',
        remark: '说明',
        options: '操作',
        limitrpm: '限制转速',
        limitrpm1: '限制转速(r/min)',
        aseconds: '限速时长',
        aspeed: '限速速度',
        aspeed1: '限速速度(s)',
        time: '时间',
        date: '日期',
        fenceManage: '围栏管理',
        selectTime: '按时间',
        selectDate: '按日期',
        dateTimeTYpe: '时间类型',
        area: '围栏区域',
        sTime: '起始时间',
        eTime: '结束时间',
        zt: {
            name: '渣土车围栏管理',
            select: '请点击画围栏区域'
        }
    },
    fenceSend: {
        checkFence: '选择围栏',
        choseVehicle: '请选择车辆',
        classification: '围栏类别'
    },
    terminalParamSet: {
        paramName: '参数名称',
        serviceParam: '服务器记录参数值',
        terminalReal: '终端实际参数',
        paramDesc: '参数描述',
        search: '查询',
        update: '更新',
        set: '设置',
        searchFalse: '查询失败',
        selectOne: '至少选择一条数据',
        searchSuccess: '查询成功',
        updateFalse: '更新失败',
        setFalse: '设置失败'
    },
    eventInfo: {
        eventinfo: '事件内容',
        alertToSelect: '请选择数据行'
    },
    phoneBook: {
        contactName: '联系人',
        phoneNumber: '手机号码',
        callStatus: '呼叫状态',
        isSend: '是否发送',
        callIn: '呼入',
        callOut: '呼出',
        callInAndOut: '呼入呼出',
        plateCode: '车牌号码',
        confirmIsSendDelAll: '您是否要对车辆电话本进行<发送删除所有>操作？',
        confirmIsSendUpdate: '您是否要对车辆电话本进行<发送更新>操作？',
        confirmIsSendAdd: '您是否要对车辆电话本进行<发送追加>操作？',
        confirmIsSendEdit: '您是否要对车辆电话本进行<发送修改>操作？',
    },
    searchForTimeAndLocation: {
        searchV: '区域查车',
        bsv: '最佳视野'
    },
    reportForm: {
        osCount: {
            plateCode: '车牌号码',
            plateColor: '车牌颜色',
            enterpriseName: '企业名称',
            fleetName: '分组名称',
            osTimes: '超速次数',
            SEtime: '起止时间',
            alarmO: '报警来源',
            alarmT: '按报警来源',
            countInfo: '统计信息',
            ost1: '持续时长(s)',
            osp: '超速位置',
            speedDetail: '明细信息',
            asTime: '报警开始时间',
            aeTime: '报警结束时间',
            asSpeed: '报警开始速度(km/h)',
            aeSpeed: '报警结束速度(km/h)',
        },
        vehicleOpt: {
            vehicleOptTotal: '车辆运行总表',
            vehicleOptDetail: '车辆运行明细',
            vehicleJia: '车架号',
            vehiclePlateCode: '车牌号',
            shebei: '设备号',
            operateTime: '运行时间',
            operateDays: '运行天数',
            operateHours: '运行小时',
            OilWear: '油耗(L)',
            begin: '初始',
            end: '结束',
            self: '本段',
            meter: '里程(km)',
            averageOil: '平均油耗(L/100km)',
            gpsMeter: 'GPS里程(km)',
            sliderMeter: '滑行里程(km)',
            sliderPro: '滑行比例',

        },
        mileageStatic: {
            mileageTotalStatic: '行驶里程统计',
            blcarGroup: '所属车队',
            blenterprise: '所属企业',
            driveTotalMileage: '行驶总里程(km)',
            dateTotalStatic: '单日行驶里程信息',
            driveDate: '行驶日期',
            lookDetail: '查看详情'
        },
        overSpeed: {
            plateCode: '车牌号码',
            searchTime: '查询时间',
            selectTime: '请选择时间',
            minSpeed: '速度底线',
            vehicleInfo: '车辆信息',
            deviceId: '设备号',
            overTimes: '超车次数',
            SEtime: '起始时间',
            speed: '速度',
            speed1: '速度(km/h)',
            location: '位置描述',
            sTime: '开始时间',
            eTime: '结束时间',
            overTime: '超速时长(s)',
            maxSpeed: '最大速度(km/h)',
            minSpeed: '最低速度(km/h)',
            avgSpeed: '平均速度(km/h)',
            rate: '超速比',
            sCar: '单车超速点明细',
            sTra: '单车轨迹点明细',
        },
        onlineRate: {
            SEtime: '起止时间',
            searchTime: '查询时间',
            selectRange: '请选择查询范围',
            selectDate: '请选择日期',
            enterpriseName: '企业名称',
            fleetName: '分组名称',
            onlineCount: '在线率统计',
            companyOnlineCount: '公司在线率统计',
            companyOnlineCountD: '公司在线率详细记录',
            fleetOnlineCount: '分组在线率',
            fleetOnlineCountD: '分组在线率详细记录',
            onlineOffCount: '上下线统计',
            offlineCount: '车辆不在线统计',
            sTime: '开始时间',
            eTime: '结束时间',
            oTimes: '在线次数',
            offTimes: '离线次数',
            onRate: '车辆在线率',
            recordTime: '记录时间',
            allV: '车辆总数',
            onV: '在线车辆数',
            offV: '离线车辆数',
            offV1: '下线车辆数'
        },
        driverIdCollection:{
            plateCode:'车牌号码',
            enterpriseName:'所属企业',
            SEtime:'起止时间',
            collectionTime:'记录采集时间',
        },
        electricCollection:{
            plateCode:'车牌号码',
            enterpriseName:'所属企业',
            SEtime:'起止时间',
            collectionTime:'记录采集时间',
        },
        inspectLog:{
            msgContext:'消息内容',
            SEtime:'起止时间',
            answerContext:'应答内容',
            creatTime:'创建时间',
            responseStatus:'应答状态',
        }
    },
    predefinedInfo: {
        type: '显示类型',
        msginfo: '信息内容',
        selectOpt1: '紧急',
        selectOpt2: '终端显示器显示',
        selectOpt3: '终端TTS播报',
        selectOpt4: '广告屏显示'
    },
    vehicleEventSend: {
        plateCode: "车牌号码",
        eventId: "事件ID",
        eventContent: "事件内容",
        createtimeStr: "下发时间",
        confirmIsSendDel: '您是否要对车辆事件进行<删除>操作?',
        confirmIsSendDelAll: '您是否要对车辆事件进行<发送删除所有>操作?',
        confirmIsSendUpdate: '您是否要对车辆事件进行<发送更新>操作?',
        confirmIsSendAdd: '您是否要对车辆事件进行<发送追加>操作?',
        confirmIsSendEdit: '您是否要对车辆事件进行<发送修改>操作?',
        alertToSelect: "请选择数据行",
        atleastOnBeSelected:'至少勾选一条'
    },
    informationType: {
        infoid: "信息服务类型ID",
        infoname: "信息服务类型名称",
        alertToSelect: "请选择数据行",
        pleaseInputNumber: "请输入正整数"
    },
    informationSendLog: {
        plateCode: "车牌号码",
        plateColor: "车辆颜色",
        infoTypeName: "信息服务类型",
        lastSendTimeStr: "开始推送时间",
        sendTimes: "推送次数",
        successed: "是否成功",
        isSendSuccess: "发送成功",
        isSendFailture: "发送失败",
    }, information: {
        infoType: "信息类型ID",
        infoTypeContent: "信息类型",
        startSendTimeStr: "开始推送时间",
        endSendTimeStr: "结束推送时间",
        information: "信息内容",
        alertToSelect: "请选择数据行",
        timeInvalidAlert: "开始推送时间不能大于结束推送时间",
        startTimeInvalidAlert: "开始推送时间不能小于当前系统时间"
    },
    //车辆信息
    vehicleInfo: {
        plateCode: '车牌号码',
        plateColor: "车牌颜色",
        mobileCode: "电话",
        vehicleOwnerName: "车主",
        driverName: "司机",
        enterpriseName: "所属企业",
        fleetName: "车辆分组",
        terminalCode: "设备编号",
        onlineStatus: "在线状态",
        adScreen: "广告屏显示",
        msgInfo: '文本内容',
        beiDouFlag: {
            type1: '中心导航信息(兼容北斗)',
            type2: 'CAN故障码信息(兼容北斗)'
        },
        alertToSelect: "请设置广告屏显示",
        alertToInputValue: "请输入文本内容"
    },
    vehicleInfomation: {
        plateCode: '车牌号码',
        plateColor: "车牌颜色",
        infoType: "信息ID",
        infoTypeName: "信息类型",
        subscribe: "点播状态",
        confirmIsSendDelAll: '您是否要对车点播设置进行<发送删除所有>操作？',
        confirmIsSendUpdate: '您是否要对车辆点播设置进行<发送更新>操作？',
        confirmIsSendAdd: '您是否要对车辆点播设置进行<发送追加>操作？',
        confirmIsSendEdit: '您是否要对车辆点播设置进行<发送修改>操作？',
        alertToSelect: "请选择数据行",
        atleastOnBeSelected: '至少勾选一条',
        unsubscribe: "未点播",
        subscribed: "已点播"
    },
    transparentInfoSend: {
        plateCode: "车牌号码",
        plateColor: "车牌颜色",
        type: "数据类型",
        data: "数据内容",
        gnssModelDetailData: "GNSS模块详细定位数据",
        roadTransICCardInfo: "道路运输证IC卡信息",
        serialCom1: "串口1 透传",
        serialCom2: "串口2 透传",
        selfDefined245: "自定义245",
        userSelfDefined: "用户自定义透传",
        alertToSelect: "请设置数据类型",
        alertToInputValue: "请输入数据内容",
        alertToSelectVehicle: "请选择车辆"
    },
    multimediaEvents: {
        id: '编号',
        channel: '通道ID',
        eventid: '多媒体数据ID',
        mediatype: '类型',
        mediaencoding: '格式',
        eventtype: '事件类型',
        eventtimeStr: '事件产生时间',
        uploadtimeStr: ' 事件上传时间',
        uploadStartTime: '上传起始时间',
        uploadEndTime: '上传结束时间',
        timeInvalidAlert: "上传起始时间不能小于上传结束时间",
        startTimeCanNotNull: "请输入上传起始时间",
        endTimeCanNotNull: "请输入上传结束时间",
    }, mediaSingleUpload: {
        eventid: "编号",
        mediaType: "类型",
        channelId: "通道",
        uploadTime: "上传时间",
        eventIdField: "下发编号：",
        deleteFlag: "删除标志：",
        remain: "保留",
        delete: "删除",
        confirmIsUpload: '您是否要执行<上传>操作？',
        eventIdIsnotAllowedNull:"请输入下发编号",
        pleaseInputNumber:"请输入长度为10的多媒体ID数值"
    },platformDataExchange:{
        plateCode:'车牌号码',
        plateColor:'车牌颜色',
        transferGroupName:'转发组名称',
        vehicleType:"车辆分类",
        header1:"普通车辆数据转发表",
        header2:"跨域货车数据转发表",
        header3:"跨域客车数据转发表",
        plateCodeShowName:"车牌号码：",
        transferGroupShowName:"转发组：",
        orderShowName:"指令：",
        pleaseToSelect:"请选择",
        ordertypeSelectOpt1:"申请交换指定车辆定位信息",
        ordertypeSelectOpt2:"取消交换指定车辆定位信息",
        ordertypeSelectOpt3:"补发车辆定位信息",
        pleaseSelectVehicle:"请选择车辆",
        pleaseSelectOrderType:"请选择指令",
        confirmIsSendOrder:"上级平台数据交换指令：是否发送指令?"
    },protocolGroup:{
        selectGroup:"选择转发组",
        protocolName:"转发协议名称",
        remark:"转发组名称",
        selectOneIsOk:"只能请选择1个协议组",
        pleaseSelectGroup:"请选择协议组",
        eventIdIsnotAllowedNull: "请输入下发编号"
    }, platformDataExchange: {
        plateCode: '车牌号码',
        plateColor: '车牌颜色',
        transferGroupName: '转发组名称',
        vehicleType: "车辆分类",
        header1: "普通车辆数据转发表",
        header2: "跨域货车数据转发表",
        header3: "跨域客车数据转发表",
        plateCodeShowName: "车牌号码：",
        transferGroupShowName: "转发组：",
        orderShowName: "指令：",
        pleaseToSelect: "请选择",
        ordertypeSelectOpt1: "申请交换指定车辆定位信息",
        ordertypeSelectOpt2: "取消交换指定车辆定位信息",
        ordertypeSelectOpt3: "补发车辆定位信息",
        pleaseSelectVehicle: "请选择车辆",
        pleaseSelectOrderType: "请选择指令",
        confirmIsSendOrder: "上级平台数据交换指令：是否发送指令?"
    }, protocolGroup: {
        selectGroup: "选择转发组",
        protocolName: "转发协议名称",
        remark: "转发组名称",
        selectOneIsOk: "只能请选择1个协议组",
        pleaseSelectGroup: "请选择协议组",
    }
}